In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [1]:
X = [
    [1, 2],
    [3, 4]
]
print(X)

[[1, 2], [3, 4]]


In [4]:
import torch

x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x)
print("Shape:", x.shape)
print("Dimensions:", x.ndim)
print("Data type:", x.dtype)
print("Device:", x.device)

tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])
Dimensions: 2
Data type: torch.int64
Device: cpu


In [17]:
import torch

# 1. Create a tensor on the CPU
cpu_tensor = torch.tensor([
    [2, 4],
    [6, 8]
])

# 2. Print CPU tensor attributes
print("--- Tensor Information ---")
print("Data:", cpu_tensor)
print("Device:", cpu_tensor.device)
print("Dimensions (ndim):", cpu_tensor.ndim)
print("Data type (dtype):", cpu_tensor.dtype)
print("Shape:", cpu_tensor.shape)

print("\n--- CPU Environment Information ---")
# Set device explicitly to CPU
device = torch.device("cpu")
print("Selected device:", device)

# Get the number of available CPU threads PyTorch can use
print("Available CPU threads:", torch.get_num_threads())

--- Tensor Information ---
Data: tensor([[2, 4],
        [6, 8]])
Device: cpu
Dimensions (ndim): 2
Data type (dtype): torch.int64
Shape: torch.Size([2, 2])

--- CPU Environment Information ---
Selected device: cpu
Available CPU threads: 10


In [18]:
import torch

# 1. Check GPU availability and set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Selected device:", device)

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

    # 2. Create inputs, weights, and bias directly on the GPU
    X_gpu = torch.tensor([
        [1.0, 2.0],
        [3.0, 4.0]
    ], device=device)

    W_gpu = torch.tensor([
        [0.5],
        [0.8]
    ], device=device)

    b_gpu = torch.tensor([0.1], device=device)

    # 3. Perform matrix multiplication and addition on GPU
    z_gpu = X_gpu @ W_gpu + b_gpu

    # 4. Print GPU details
    print("\n--- GPU Output ---")
    print("z_gpu:\n", z_gpu)
    print("Device:", z_gpu.device)
    print("Shape:", z_gpu.shape)

    # 5. Cross-check against CPU
    X_cpu = X_gpu.cpu()
    W_cpu = W_gpu.cpu()
    b_cpu = b_gpu.cpu()
    z_cpu = X_cpu @ W_cpu + b_cpu

    print("\n--- Cross-Check ---")
    print("CPU result matches GPU result:", torch.allclose(z_cpu, z_gpu.cpu()))
else:
    print("CUDA is not available on this system. Please check your GPU setup or drivers.")

Selected device: cpu
CUDA is not available on this system. Please check your GPU setup or drivers.


In [19]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)

x = x.to(device)

print("Tensor:", x)
print("Device:", x.device)

Tensor: tensor([1., 2., 3.])
Device: cpu


In [ ]:
import torch

dev = input(
    "Enter device (1 or 2):\n"
    "1. CPU\n"
    "2. CUDA\n"
)

if dev == "1":
    device = torch.device("cpu")

elif dev == "2":
    if torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        print("CUDA is not available. Using CPU.")
        device = torch.device("cpu")

else:
    print("Invalid choice. Using CPU.")
    device = torch.device("cpu")


print("\nSelected device:", device)


# Create tensor

x = torch.tensor(
    [[1, 2],
     [3, 4]],
    dtype=torch.float32
)

print("\nOriginal tensor:")
print(x)
print("Device:", x.device)


# Move tensor

x = x.to(device)

print("\nTensor after moving:")
print(x)
print("Device:", x.device)


# Perform operation

y = x @ x

print("\nResult:")
print(y)
print("Device:", y.device)

In [20]:
import torch

# Inputs
x1 = torch.tensor([8.0],
                  device=torch.device("cuda" if torch.cuda.is_available() else "cpu"))
x2 = torch.tensor([98.0],
                  device=torch.device("cuda" if torch.cuda.is_available() else "cpu"))

# Weights
w1 = torch.tensor(0.5)
w2 = torch.tensor(0.4)

# Bias
b = torch.tensor(2.0)

# Weighted sum
z = (x1 * w1) + (x2 * w2) + b

prediction = torch.sigmoid(z)

print("z =", z)
print("Prediction =", prediction)

z = tensor([45.2000])
Prediction = tensor([1.])


In [21]:
import torch

x = torch.tensor(5.0)

w = torch.tensor(
    2.0,
    requires_grad=True
)

y = x * w

print("y =", y)

y.backward()

print("Gradient of w =", w.grad)

y = tensor(10., grad_fn=<MulBackward0>)
Gradient of w = tensor(5.)


In [22]:
import torch

x = torch.tensor(5.0)

w = torch.tensor(
    2.0,
    requires_grad=True
)

target = torch.tensor(20.0)

prediction = x * w

loss = (target - prediction) ** 2

print("Prediction:", prediction)
print("Loss:", loss)

loss.backward()

print("Gradient:", w.grad)

Prediction: tensor(10., grad_fn=<MulBackward0>)
Loss: tensor(100., grad_fn=<PowBackward0>)
Gradient: tensor(-100.)


In [30]:
import torch

x = torch.tensor(5.0)

w = torch.tensor(
    2.0,
    requires_grad=True
)

target = torch.tensor(20.0)

lr = 0.01
for epoch in range(12):

    # Forward
    prediction = x * w

    # Loss
    loss = (target - prediction) ** 2

    # Backward
    loss.backward()

    print(
        f"Epoch: {epoch + 1} | "
        f"Weight: {w.item():.4f} | "
        f"Prediction: {prediction.item():.4f} | "
        f"Loss: {loss.item():.4f} | "
        f"Gradient: {w.grad.item():.4f}"
    )

    # Update
    with torch.no_grad():
        w -= lr * w.grad

    # Clear gradient
    w.grad.zero_()

    print(f"Updated Weight: {w.item():.4f}")
    print()

Epoch: 1 | Weight: 2.0000 | Prediction: 10.0000 | Loss: 100.0000 | Gradient: -100.0000
Updated Weight: 3.0000

Epoch: 2 | Weight: 3.0000 | Prediction: 15.0000 | Loss: 25.0000 | Gradient: -50.0000
Updated Weight: 3.5000

Epoch: 3 | Weight: 3.5000 | Prediction: 17.5000 | Loss: 6.2500 | Gradient: -25.0000
Updated Weight: 3.7500

Epoch: 4 | Weight: 3.7500 | Prediction: 18.7500 | Loss: 1.5625 | Gradient: -12.5000
Updated Weight: 3.8750

Epoch: 5 | Weight: 3.8750 | Prediction: 19.3750 | Loss: 0.3906 | Gradient: -6.2500
Updated Weight: 3.9375

Epoch: 6 | Weight: 3.9375 | Prediction: 19.6875 | Loss: 0.0977 | Gradient: -3.1250
Updated Weight: 3.9688

Epoch: 7 | Weight: 3.9688 | Prediction: 19.8438 | Loss: 0.0244 | Gradient: -1.5625
Updated Weight: 3.9844

Epoch: 8 | Weight: 3.9844 | Prediction: 19.9219 | Loss: 0.0061 | Gradient: -0.7812
Updated Weight: 3.9922

Epoch: 9 | Weight: 3.9922 | Prediction: 19.9609 | Loss: 0.0015 | Gradient: -0.3906
Updated Weight: 3.9961

Epoch: 10 | Weight: 3.9961 | 

In [33]:
import torch
import torch.nn as nn

class SimpleModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.w = nn.Parameter(
            torch.tensor(2.0)
        )

    def forward(self, x):
        return x * self.w
model = SimpleModel()
print(model)

SimpleModel()


In [37]:
class MyNetwork(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(10, 32)
        self.layer2 = nn.Linear(32, 16)
        self.output = nn.Linear(16, 1)

    def forward(self, x):

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.output(x)

        return x

In [36]:
import torch
import torch.nn as nn


class SimpleModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.w = nn.Parameter(
            torch.tensor(2.0)
        )

    def forward(self, x):
        return x * self.w


model = SimpleModel()

x = torch.tensor(5.0)
target = torch.tensor(20.0)

prediction = model(x)

loss = (target - prediction) ** 2

loss.backward()

print("Prediction:", prediction.item())
print("Loss:", loss.item())
print("Weight:", model.w.item())
print("Gradient:", model.w.grad.item())

Prediction: 10.0
Loss: 100.0
Weight: 2.0
Gradient: -100.0


In [9]:
import torch
import torch.nn as nn

layer = nn.Linear(
    in_features=4,
    out_features=1
)

print(layer)
x = torch.tensor([[5.0,6.0,7.0,8.0]])

output = layer(x)

print("Output:", output)

Linear(in_features=4, out_features=1, bias=True)
Output: tensor([[-0.2201]], grad_fn=<AddmmBackward0>)


In [10]:
import torch
import torch.nn as nn

layer = nn.Linear(
    in_features=1,
    out_features=1
)

with torch.no_grad():
    layer.weight.fill_(2.0)
    layer.bias.fill_(1.0)

x = torch.tensor([[5.0]])

output = layer(x)

print("Weight:", layer.weight)
print("Bias:", layer.bias)
print("Output:", output)

Weight: Parameter containing:
tensor([[2.]], requires_grad=True)
Bias: Parameter containing:
tensor([1.], requires_grad=True)
Output: tensor([[11.]], grad_fn=<AddmmBackward0>)


In [11]:
import torch
import torch.nn as nn

layer = nn.Linear(
    in_features=1,
    out_features=1
)

with torch.no_grad():
    layer.weight.fill_(2.0)
    layer.bias.fill_(1.0)

x = torch.tensor([[5.0]])

output = layer(x)

print("Weight:", layer.weight)
print("Bias:", layer.bias)
print("Output:", output)

Weight: Parameter containing:
tensor([[2.]], requires_grad=True)
Bias: Parameter containing:
tensor([1.], requires_grad=True)
Output: tensor([[11.]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
import torch.nn as nn

layer = nn.Linear(
    in_features=2,
    out_features=1
)

with torch.no_grad():
    layer.weight[0] = torch.tensor([0.5, 0.4])
    layer.bias.fill_(2.0)

x = torch.tensor([
    [8.0, 98.0]
])

output = layer(x)

print("Output:", output)

Output: tensor([[45.2000]], grad_fn=<AddmmBackward0>)


In [1]:
import torch
import torch.nn as nn

layer = nn.Linear(
    in_features=2,
    out_features=1
)

with torch.no_grad():
    layer.weight[0] = torch.tensor([0.5, 0.4])
    layer.bias.fill_(2.0)

x = torch.tensor([
    [8.0, 98.0]
])

output = layer(x)

print("Input:", x)
print("Weight:", layer.weight)
print("Bias:", layer.bias)
print("Output:", output)

print("\nParameters:")
for parameter in layer.parameters():
    print(parameter)

Input: tensor([[ 8., 98.]])
Weight: Parameter containing:
tensor([[0.5000, 0.4000]], requires_grad=True)
Bias: Parameter containing:
tensor([2.], requires_grad=True)
Output: tensor([[45.2000]], grad_fn=<AddmmBackward0>)

Parameters:
Parameter containing:
tensor([[0.5000, 0.4000]], requires_grad=True)
Parameter containing:
tensor([2.], requires_grad=True)


In [13]:
import torch
import torch.nn as nn


# Dataset

X = torch.tensor([
    [1, 1],
    [1, 2],
    [2, 1],
    [2, 2],
    [5, 5],
    [5, 6],
    [6, 5],
    [6, 6]
], dtype=torch.float32)


Y = torch.tensor([
    [0],
    [0],
    [0],
    [0],
    [1],
    [1],
    [1],
    [1]
], dtype=torch.float32)


# Model

model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)


# Loss function

loss_function = nn.MSELoss()


# Learning rate

lr = 0.1


# Training

for epoch in range(10000):

    # Forward
    prediction = model(X)

    # Loss
    loss = loss_function(
        prediction,
        Y
    )

    # Backward
    loss.backward()

    # Update parameters
    with torch.no_grad():

        for parameter in model.parameters():

            parameter -= lr * parameter.grad

    # Clear gradients
    for parameter in model.parameters():

        parameter.grad.zero_()

    if (epoch + 1) % 1000 == 0:

        print(
            f"Epoch: {epoch + 1:3d} | "
            f"Loss: {loss.item():.4f}"
        )

Epoch: 1000 | Loss: 0.0149
Epoch: 2000 | Loss: 0.0071
Epoch: 3000 | Loss: 0.0046
Epoch: 4000 | Loss: 0.0034
Epoch: 5000 | Loss: 0.0027
Epoch: 6000 | Loss: 0.0022
Epoch: 7000 | Loss: 0.0019
Epoch: 8000 | Loss: 0.0017
Epoch: 9000 | Loss: 0.0015
Epoch: 10000 | Loss: 0.0013


In [14]:
import torch
import torch.nn as nn


# Dataset

X = torch.tensor([
    [1, 1],
    [1, 2],
    [2, 1],
    [2, 2],
    [5, 5],
    [5, 6],
    [6, 5],
    [6, 6]
], dtype=torch.float32)


Y = torch.tensor([
    [0],
    [0],
    [0],
    [0],
    [1],
    [1],
    [1],
    [1]
], dtype=torch.float32)


# Model

model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)


# Loss function

loss_function = nn.MSELoss()


# Learning rate

lr = 0.1


# Training

for epoch in range(10000):

    # Forward
    prediction = model(X)

    # Loss
    loss = loss_function(
        prediction,
        Y
    )

    # Backward
    loss.backward()

    # Update parameters
    with torch.no_grad():

        for parameter in model.parameters():

            parameter -= lr * parameter.grad

    # Clear gradients
    for parameter in model.parameters():

        parameter.grad.zero_()

    if (epoch + 1) % 1000 == 0:

        print(
            f"Epoch: {epoch + 1:3d} | "
            f"Loss: {loss.item():.4f}"
        )
print("\nFinal Predictions:")

with torch.no_grad():
    predictions = model(X)

    for x, prediction, actual in zip(X, predictions, Y):
        print(
            f"Input: {x.tolist()} | "
            f"Prediction: {prediction.item():.4f} | "
            f"Actual: {actual.item():.0f}"
        )

Epoch: 1000 | Loss: 0.0155
Epoch: 2000 | Loss: 0.0072
Epoch: 3000 | Loss: 0.0047
Epoch: 4000 | Loss: 0.0034
Epoch: 5000 | Loss: 0.0027
Epoch: 6000 | Loss: 0.0023
Epoch: 7000 | Loss: 0.0019
Epoch: 8000 | Loss: 0.0017
Epoch: 9000 | Loss: 0.0015
Epoch: 10000 | Loss: 0.0013

Final Predictions:
Input: [1.0, 1.0] | Prediction: 0.0127 | Actual: 0
Input: [1.0, 2.0] | Prediction: 0.0319 | Actual: 0
Input: [2.0, 1.0] | Prediction: 0.0310 | Actual: 0
Input: [2.0, 2.0] | Prediction: 0.0755 | Actual: 0
Input: [5.0, 5.0] | Prediction: 0.9541 | Actual: 1
Input: [5.0, 6.0] | Prediction: 0.9815 | Actual: 1
Input: [6.0, 5.0] | Prediction: 0.9810 | Actual: 1
Input: [6.0, 6.0] | Prediction: 0.9925 | Actual: 1
