# PyTorch Basics

In [3]:
import torch
print(torch.__version__)
x = torch.tensor([1, 2, 3, 4])
print(x)
print(type(x))

2.13.0+cpu
tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [7]:
import torch
print(torch.__version__)
x = torch.tensor([1, 2, 3, 4],
                 dtype=torch.float32
)
print(x)
print(x.dtype)

print(x)
print(x.shape)

2.13.0+cpu
tensor([1., 2., 3., 4.])
torch.float32
tensor([1., 2., 3., 4.])
torch.Size([4])


In [9]:
import torch
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [12]:
x = torch.zeros(3)

print(x)
x = torch.ones(2, 3)

print(x)
x = torch.rand(2, 3)

print(x)

tensor([0., 0., 0.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9824, 0.7753, 0.2968],
        [0.4285, 0.0828, 0.6843]])


In [13]:
a = torch.tensor([1, 2, 3, 4])

b = torch.zeros(2, 3)

c = torch.ones(3, 2)

d = torch.rand(4, 5)

print("a:", a)
print("a shape:", a.shape)

print()

print("b shape:", b.shape)
print("c shape:", c.shape)
print("d shape:", d.shape)

a: tensor([1, 2, 3, 4])
a shape: torch.Size([4])

b shape: torch.Size([2, 3])
c shape: torch.Size([3, 2])
d shape: torch.Size([4, 5])


In [29]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(x)
print(x.shape)
print(x[0, 0])
print(x[1, 2])
print(x[0])  #print(x[1:,])
print(x[:,2])

#slicing
print(x[0:2])
print(x[0:2, 1:3])
print(x[-1])

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
torch.Size([3, 3])
tensor(10)
tensor(60)
tensor([10, 20, 30])
tensor([30, 60, 90])
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([[20, 30],
        [50, 60]])
tensor([70, 80, 90])


In [32]:
#tensor opertations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)
print(a * b)
print(b - a)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([3, 3, 3])


In [ ]:
#scalar operations
x=torch.tensor([1,2,3])
print(x+10)

tensor([11, 12, 13])


In [34]:
#scalar operations
x=torch.tensor([1,2,3])
print(x[0]+10)

tensor(11)


In [42]:
#matrix multiplication

x=torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

w=torch.tensor([
    [0.7,0.3],
    [0.6,0.4]
], dtype=torch.float32)
print(x @ w)

tensor([[1.9000, 1.1000],
        [4.5000, 2.5000]])


In [1]:
import torch.nn as nn
layer = nn.Linear(2, 2)
print(layer)
print(layer.weight)
print(layer.bias)

Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[-0.4511, -0.0243],
        [-0.3296,  0.2161]], requires_grad=True)
Parameter containing:
tensor([ 0.5474, -0.2494], requires_grad=True)


In [8]:
import torch
X = torch.tensor([
    [1, 5],
    [2, 6],
    [3, 6],
    [4, 7],
    [5, 7],
    [6, 8],
    [7, 8],
    [8, 9]
], dtype=torch.float32)
y = torch.tensor([
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1
], dtype=torch.float32)
model = nn.Linear(2, 1)
output = model(X)

print(output)
print(output.shape)

tensor([[-0.6617],
        [-0.5585],
        [-0.1528],
        [-0.0497],
        [ 0.3560],
        [ 0.4592],
        [ 0.8648],
        [ 0.9680]], grad_fn=<AddmmBackward0>)
torch.Size([8, 1])


In [3]:
import torch
from torch import nn
X = torch.tensor([
    [1, 5],
    [2, 6],
    [3, 6],
    [4, 7],
    [5, 7],
    [6, 8],
    [7, 8],
    [8, 9]
], dtype=torch.float32)
y = torch.tensor([
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1
], dtype=torch.float32)
model = nn.Linear(2, 1)
predictions = model(X)
loss_fn = nn.MSELoss()

loss = loss_fn(predictions, y)

print("Loss:", loss)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
optimizer.zero_grad()
predictions = model(X)
loss = loss_fn(predictions, y)
loss.backward()
print("\n")
print(model.weight.grad)
print(model.bias.grad)
optimizer.step()


Loss: tensor(28.3035, grad_fn=<MseLossBackward0>)


tensor([[52.9916, 74.2742]])
tensor([10.0030])


In [1]:
import torch
from torch import nn

X = torch.tensor([
    [1, 5],
    [2, 6],
    [3, 6],
    [4, 7],
    [5, 7],
    [6, 8],
    [7, 8],
    [8, 9]
], dtype=torch.float32)

y = torch.tensor([
    [0],
    [0],
    [0],
    [1],
    [1],
    [1],
    [1],
    [1]
], dtype=torch.float32)

model = nn.Linear(2, 1)

loss_fn = nn.BCEWithLogitsLoss()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

print("Before:")
print("Weight:", model.weight)
print("Bias:", model.bias)
for epoch in range(1,100000):

    optimizer.zero_grad()

    predictions = model(X)

    loss = loss_fn(predictions, y)

    loss.backward()

    optimizer.step()

    if epoch % 10000 == 0:
        print(
            f"Epoch {epoch} | "
            f"Loss: {loss.item():.4f} | "
            f"Weight: {model.weight.data} | "
            f"Bias: {model.bias.data}"
        )
with torch.no_grad():
    logits = model(X)
    probabilities = torch.sigmoid(logits)
    predictions = (probabilities >= 0.5).float()

print("Probabilities:")
print(probabilities)

print("Predicted classes:")
print(predictions)

print("Actual:")
print(y)

accuracy = (predictions == y).float().mean()

print("Accuracy:", accuracy.item())

Before:
Weight: Parameter containing:
tensor([[0.5990, 0.2367]], requires_grad=True)
Bias: Parameter containing:
tensor([0.3199], requires_grad=True)
Epoch 10000 | Loss: 0.0820 | Weight: tensor([[ 3.9172, -1.9524]]) | Bias: tensor([-0.8931])
Epoch 20000 | Loss: 0.0607 | Weight: tensor([[ 5.1308, -2.5214]]) | Bias: tensor([-1.4537])
Epoch 30000 | Loss: 0.0485 | Weight: tensor([[ 6.0486, -2.9487]]) | Bias: tensor([-1.8940])
Epoch 40000 | Loss: 0.0402 | Weight: tensor([[ 6.8009, -3.2982]]) | Bias: tensor([-2.2587])
Epoch 50000 | Loss: 0.0343 | Weight: tensor([[ 7.4397, -3.5948]]) | Bias: tensor([-2.5695])
Epoch 60000 | Loss: 0.0298 | Weight: tensor([[ 7.9942, -3.8520]]) | Bias: tensor([-2.8397])
Epoch 70000 | Loss: 0.0263 | Weight: tensor([[ 8.4835, -4.0790]]) | Bias: tensor([-3.0784])
Epoch 80000 | Loss: 0.0235 | Weight: tensor([[ 8.9209, -4.2819]]) | Bias: tensor([-3.2917])
Epoch 90000 | Loss: 0.0213 | Weight: tensor([[ 9.3160, -4.4651]]) | Bias: tensor([-3.4845])
Probabilities:
tensor(